version: '3.9'

networks:
  backend:
    name: network-backend
    external: false
  frontend:
    name: network-front

services:
  database:
    container_name: mysql-cont
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always
    networks:
      - backend
    volumes:
      - D:\docker\database:/var/lib/mysql
  phpmyadmin:
    container_name: admin-cont
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=database
    ports:
      - 8081:80
    restart: always
    networks:
      - backend
      - frontend
  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    networks:
      - backend
      - frontend
    depends_on:
      - database
